
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: 
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Build with Gradle
        run: ./gradlew clean check --stacktrace
      - name: Upload snapshot (main only)
        run: ./gradlew uploadArchives -PSONATYPE_NEXUS_USERNAME/main' && github.event_name != 'pull_request' && matrix.java_version == '1.8'
